### ISSUE TITLE
The kernel version check comparison is not correct

### ISSUE THREAD

**Issue by raghavendra-talur** [openshift/openshift-ansible#11883]
#### Description

We tried installing a new OCP cluster using release-3.11 branch master and it failed with the following error 

```
Failure summary:


  1. Hosts:    ci-ocp-3-11-z-ocs-3-11-4-cns-compute-0, ci-ocp-3-11-z-ocs-3-11-4-cns-infra-0, ci-ocp-3-11-z-ocs-3-11-4-cns-master-0, ci-ocp-3-11-z-ocs-3-11-4-cns-storage-1, ci-ocp-3-11-z-ocs-3-11-4-cns-storage-2, ci-ocp-3-11-z-ocs-3-11-4-cns-storage-3
     Play:     Install packages necessary for installer
     Task:     Ensure minimum kernel version
     Message:  The installed kernel version does not meet the required minimum for RHEL 7.7.
               Please update the kernel before continuing.
               Minimum Kernel Version: 3.10.0-1062.el7
               Installed Kernel Version: 3.10.0-1062.1.1.el7.x86_64
               Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1749024

```

Provide a brief description of your issue here. For example:
Installation of OCP 3.11 fails.

##### Version
3.11

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Operating system is RHEL 7.7

Looks like this could be because of https://github.com/openshift/openshift-ansible/pull/11881

**Comment by mtnbikenc** [comment]
Thanks for reporting this issue.  I'm still testing #11889 but it would be great if you can test this change to make sure it resolves the problem in your environment.

**Comment by mtnbikenc** [comment]
Fixed in #11889

**Comment by raghavendra-talur** [comment]
@mtnbikenc Thanks! We tested the fix and it is working.

**Comment by aliartiza75** [comment]
hi @raghavendra-talur, I am using the openshift-ansible version 3.11 but still getting the same issue, can you help me out on how you resolved this issue?
