### ISSUE TITLE
No hostsubnets created after a successfull Ansible run

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/openshift-ansible#1261]
Hi,

We are trying to install OpenShift Origin using the Ansible playbook on a few Openstack VMs. We are following https://docs.openshift.org/latest/install_config/install/advanced_install.html to have an installation with multiple masters and a standalone etcd cluster. 

Running the playbook as stated in the docs works and finishes without any error. 
The problem is that the hostsubnets are not created during the installation and running `oc get hostsubnets` doesn't return anything.

We are setting these values in the inventory file, but no luck:
```
osm_cluster_network_cidr=10.1.0.0/16
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
```
We have also tried with the default values for those properties but same behavior.

Is this normal or are we missing something? Thanks

**Comment by detiber** [comment]
@AlbertoPeon are there any errors in the node logs? `journalctl -u origin-node -l`?

**Comment by abutcher** [comment]
This looks like it may be a problem with the `origin-master-controllers` service (assuming native ha), any logs there? `journalctl -u origin-master-controllers -l`

**Comment by AlbertoPeon** [comment]
Hi @detiber @abutcher,

I think we've understood where the problem comes from. The cause is that the IP addresses of the nodes are empty.
```
# oc get nodes/oonode001 --template="{{.status.addresses}}"
[map[type:ExternalIP address:]]
```
These values are populated as a result of a query to the Openstack API (using openstack as cloud provider). Apparently, OpenShift is not able to parse them correctly. We've tracked the error upstream and the exact problem seems to be: https://github.com/kubernetes/kubernetes/issues/18409

It would be great if these values could be overriden using the common settings per node (as defined here: https://github.com/openshift/openshift-ansible/blob/master/README_origin.md#overriding-detected-ip-addresses-and-hostnames)

**Comment by detiber** [comment]
@AlbertoPeon this should be fixed in the latest origin release (1.1.2)

**Comment by AlbertoPeon** [comment]
@detiber we have just tried an installation of origin 1.1.2 and the issue is still not fixed. Please not that the root cause of our problem is the Openstack integration (ip addresses for VMs cannot be computed) and not the SDN.

The code has been fixed in Kubernetes but it hasn't yet in Openshift. I'm optimistic it will make 1.2 :)

**Comment by detiber** [comment]
@AlbertoPeon Ah, I thought the changes had landed in the 1.1.2 build but I was mistaken...  The upstream fix should be in the 1.1.3 build that was just released though.

**Comment by AlbertoPeon** [comment]
This was fixed in 1.1.4
