### ISSUE TITLE
FAILED - RETRYING: HANDLER: openshift_master: Verify API Server (120 tries left)

### ISSUE THREAD

**Issue by dvohra** [openshift/openshift-ansible#2271]
Getting message (repeated 120 times)
`FAILED - RETRYING: HANDLER: openshift_master: Verify API Server (120 tries left)
`

And subsequently:
`FAILED! => {"changed": false, "cmd": ["curl", "--silent", "--cacert", "/etc/origin/master/ca-bundle.crt", "https://ec2-54-81-143-129.compute-1.amazonaws.com:8443/healthz/ready"], "delta": "0:00:05.600946", "end": "2016-08-08 22:34:36.218520", "failed": true, "rc": 51, "start": "2016-08-08 22:34:30.617574", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": ["Consider using get_url or uri module rather than running curl"]}`

**Comment by dvohra** [comment]
Seems to be because of DNS not being configured.

**Comment by dvohra** [comment]
The NetworkManager was to be installed. Issue is fixed and may be closed, but refer the request to install NetworkManager automatically.

**Comment by lannyMa** [comment]
sorry i cannnot unterstand

**Comment by poltorres7** [comment]
Hello I have the same error "Verify API server"
I have installed the NetworkManager but it still failing.

Does any body have found a solution?

**Comment by samvarankashyap** [comment]
Facing the same issue ...
Anyone anyother solution

**Comment by rushabh268** [comment]
@abutcher Seeing the same issue on Atomic cluster where NetworkManager is installed on the master node

**Comment by poltorres7** [comment]
Hi @samvarankashyap & @rushabh268 I've solve it.  The problem was that I had a proxy configurated and openshift was going out in that route, when I disable it, the request was resolved it.

**Comment by tusharsanas** [comment]
Hi,

I am facing the same issues FAILED - RETRYING: HANDLER: openshift_master: Verify API Server (120 tries left)

Few details of my setup:
3 Master, 3 Compute, 3 Infra and 3 GlusterFS.
1 External LB and another 1 Internal LB

I did check with below curl command 
curl -k -vvv https://master002-internal.amosdemo.io:8443/healthz/ready

But my master is not able to connect internal load balancer.
My internal load balancer is network LB, and all the master instances attached to internal LB are healthy.

Please can anyone help me to resolve above issue.
