### ISSUE TITLE
Can't deploy GlusterFS

### ISSUE THREAD

**Issue by braun1928** [openshift/openshift-ansible#4394]
Hello,
I've deployed a new cluster, and wanted to use glusterfs as the storage backend. Following the README in playbooks/byo/openshift-glusterfs, I created the group glusterfs and added glusterfs_devices to the nodes:
```
[OSEv3:children]
masters
nodes
etcd
lb
glusterfs
(...)
[glusterfs]
osh-node-0[1:3].homo.ocp.braun.local glusterfs_devices='[ "/dev/sdb" ]'
```

And run the config.yml playbook. It **always** runs the task to create temp directory (on the first master), and **all** the following tasks it skips until the "Delete temp directory", and finishes, not deploying glusterfs and heketi.

Does it need to have any other variable or label to make it work? The README doesn't help, it's too simple and the data there didn't work.

##### Version
```
ansible 2.3.0.0
openshift-ansible-3.6.89.4-1
```
##### Steps To Reproduce
1. Deploy normally with playbooks/byo/config.yml, without glusterfs group
2. Add glusterfs group to inventory
3. Deploy with playbooks/byo/openshift-glusterfs/config.yml

##### Expected Results
Hoped to have gluster and heketi deployed.

##### Observed Results
Skips every time, no matter what label I put in the hosts, or what parameters I change.

Inventory: https://gist.githubusercontent.com/braun1928/771d8a79ec29cbaf3d823511d0d4e9d1/raw/dde7e242b410cefdc4824f5b0a70bfeb14a4f2e4/hosts
Ansible output: https://gist.githubusercontent.com/braun1928/771d8a79ec29cbaf3d823511d0d4e9d1/raw/dde7e242b410cefdc4824f5b0a70bfeb14a4f2e4/ansible.log

##### Additional Information
```
CentOS Linux release 7.3.1611 (Core)
```

**Comment by abutcher** [comment]
@jarrpa Could you take a look at this when you get a chance?

**Comment by jarrpa** [comment]
I think this is fixed by #4245.

**Comment by braun1928** [comment]
Awesome. I got that branch, and I'll do some testing, while it's not merged.
If anything happens, I'll report here.
Thanks!

**Comment by braun1928** [comment]
It's getting better:
1) First error was that it didn't find the templates for v1.5. Created a symbolic link from v3.6 just to pass the task (it didn't seemed to me that it was a problem);
2) The gluster pods were created!
3) After the "Deploy GlusterFS pods", "Wait for GlusterFS pods" failed:

The conditional check 'glusterfs_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions') | oo_collect(attribute='status', filters={'type': 'Ready'}) | map('bool') | select | list | count == glusterfs_nodes | count' failed. The error was: 'list' object has no attribute 'get'

**Comment by jarrpa** [comment]
@braun1928 Is that with the #4245 branch? I thought I fixed that exact error there...

**Comment by braun1928** [comment]
@jarrpa I messed up a bit too much with branches =/ ... But now, with the correct one (sorry!), it still happens. At least it failed **after** a first try on the task Wait for GlusterFS, but with the same message:

FAILED - RETRYING: Wait for GlusterFS pods (30 retries left) **this is new**

The conditional check 'glusterfs_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions') | oo_collect(attribute='status', filters={'type': 'Ready'}) | map('bool') | select | list | count == glusterfs_nodes | count' failed. The error was: 'list' object has no attribute 'get'

**Comment by jarrpa** [comment]
@braun1928 That's odd. Can you rerun ansible-playbook with `-vvv` and paste the output of the failing task?

**Comment by braun1928** [comment]
@jarrpa done: https://gist.github.com/braun1928/45b5ebeff24d820dd8e8cc50f8e6772a/raw/a86ece620fb0ee634f23f3af8aa703135d95c56a/ansible.log

**Comment by jarrpa** [comment]
@braun1928 ....I'm baffled. I can't reproduce this. :( Just to check, can you find `filter_plugins/oo_filters.py` and paste the `oo_collect` function? It should look like [this](https://github.com/openshift/openshift-ansible/blob/master/filter_plugins/oo_filters.py#L132-L186).

**Comment by braun1928** [comment]
@jarrpa the whole file is the same =/

**Comment by jarrpa** [comment]
@braun1928 Hmm... okay, we'll need to troubleshoot harder, then. If you're willing and able, see what the following gets you:

1. Comment out the failing conditional. Leave the first one, so we at least have one item in the list.
2. Insert the following task immediately after the `Wait for GlusterFS pods` task:
```
- fail
    msg: "{{ glusterfs_pods.results.results[0]['items'] }}"
```
3. Rerun the install with `--vvv`, paste the fail task's output here and we'll see if it shows anything interesting. :)

**Comment by braun1928** [comment]
@jarrpa done it. I really am interested in solving this, but I can only do it during the weekdays.
Well, the output is @ https://gist.github.com/braun1928/001bacb2245382fd153aed0e4708680f

**Comment by jarrpa** [comment]
@braun1928 dammit, that looks good, too. Okay, so now things are going to get tedious. :(

Replace the above with the following:
```
- debug:
    msg: "{{ glusterfs_pods.results.results[0]['items'] }}"

- fail
```
Then rerun the playbook, but keep adding the `| <foo>` parts from the failing conditional one at a time until the `debug` play fails. Keep track of the debug output for each run. We are interested in knowing when it fails and what the output was from the last successful debug.

I'm still trying to find a way to reproduce this, so apologies I can't do this myself.

**Comment by braun1928** [comment]
@jarrpa it failed:
`The conditional check 'glusterfs_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions') | oo_collect(attribute='status', filters={'type': 'Ready'})' failed. The error was: 'list' object has no attribute 'get'`

I've put on https://gist.github.com/braun1928/81504ec98e9648ec296deee577dfc51d the results from the task "Wait for GlusterFS pods" of each run.

It's no problem, I can test it :)

**Comment by erinboyd** [comment]
Network related maybe??

**Comment by jarrpa** [comment]
@braun1928 So wait, did you first test if `glusterfs_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions')` worked?

@erinboyd No, the pod information is being fetched correctly.

**Comment by braun1928** [comment]
@jarrpa yes, that's it. When added the second oo_collect, it failed.

**Comment by jarrpa** [comment]
@braun1928 what was the output of the debug task with only one oo_collect? If you've pasted it already, can you isolate it?

**Comment by braun1928** [comment]
@jarrpa I did, it's in that gist, the second file. Sorry, I didn't make it clear enough. https://gist.github.com/braun1928/81504ec98e9648ec296deee577dfc51d#file-ansible-log-ok

**Comment by jarrpa** [comment]
@braun1928 That can't be it. The output you're pointing to is the output that I'd expect for `glusterfs_pods.results.results[0]['items']`. The output of `glusterfs_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions')` should be a list of lists, where each sublist is the contents of the `status.conditions` variable from the first results.

**Comment by braun1928** [comment]
@jarrpa ha! sorry! I changed the condition, not the debug message. =/ Well, it failed anyway when adding the second `oo_collect`.
I've put the output in https://gist.github.com/braun1928/a08b202f75a3528d25265ea461ee642b
The first task is `glusterfs_pods.results.results[0]['items'] | oo_collect(attribute='status.conditions')`, the second, adding `oo_collect(attribute='status', filters={'type': 'Ready'})`

**Comment by jarrpa** [comment]
@braun1928 Perfect!

Hmm... looks like something is out of date. Can you check `/usr/share/ansible_plugins/filter_plugins/oo_filters.py` line 157 and verify it's exactly `all([d.get(key, None) == filters[key] for key in filters]))]`? If so, you're using outdated code as that code should be closer to line 180.

**Comment by sdodson** [comment]
Problems like these often occur if you have the openshift-ansible rpms installed and you're attempting to run from a github checkout. Is that possible in your scenario? If so please remove the rpms if you're using a github checkout.

**Comment by jarrpa** [comment]
@braun1928 Happy to help! :) Please feel free to keep troubleshooting here until you have success. ;)

**Comment by braun1928** [comment]
@jarrpa well, it finished deploying glusterfs :) It's available as persistent storage in the web ui. Heketi fails in task `Check if GlusterFS registry volume exists`, returning `Error: signature is invalid`. =/
Didn't have the time to debug this yet.

**Comment by braun1928** [comment]
Hey @jarrpa, I got back to test this, and it all worked with the latest commit. Thanks for all the help!
