### ISSUE TITLE
Failed conditional check for etcd_common when deploying

### ISSUE THREAD

**Issue by jameslabocki** [openshift/openshift-ansible#4609]
#### Description

When deploying the following error occurs:

https://paste.fedoraproject.org/paste/wkVhhxEt0SRfDOXgf-q~Cw

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```# ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

If you're operating from a **git clone**:

* The output of `git describe`

```
# git describe
openshift-ansible-3.6.123.1001-1
```

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.5.78-1.git.0.f7be576.el7.noarch
openshift-ansible-3.5.78-1.git.0.f7be576.el7.noarch
```

##### Steps To Reproduce
We happen to be running this from the ose-on-aws.py script included here:
https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible

##### Expected Results
We expect the installation not to have the error

```
https://paste.fedoraproject.org/paste/wkVhhxEt0SRfDOXgf-q~Cw
```

##### Observed Results
Installation fails with the following error:

```
https://paste.fedoraproject.org/paste/wkVhhxEt0SRfDOXgf-q~Cw
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

ose-on-aws.py command syntax:
```
./ose-on-aws.py --create-vpc=yes --keypair=OSE-key --rhsm-user=*** --rhsm-password=*** --public-hosted-zone=strategicdesign.io --rhsm-pool=*** --github-client-secret=*** --github-organization=strategicdesignteam --github-client-id=*** --deploy-openshift-metrics=true

**Comment by jameslabocki** [comment]
@ingvagabund @sdodson suggested I tag you in this issue

**Comment by sdodson** [comment]
I'm not familiar with that inventory script but can you verify whether or not it's placing hosts in the [etcd] group?

**Comment by jameslabocki** [comment]
@sdodson you might be on to something. Do you happen to know what package provides the AWS inventory script? Maybe we have an old version?

**Comment by ingvagabund** [comment]
That looks very strange. The `r_etcd_common_action` is set to `noop` by default. So it can not be undefined. Unless the Ansible 2.3.1 is doing something messy. Currently, we do not support Ansible `2.3`. Can you rerun it again with Ansible `2.2.*`?

**Comment by j00p34** [comment]
This happens also in Ansible 2.2.* I think it's the same as #4121 fixed by #4687

**Comment by ingvagabund** [comment]
https://github.com/openshift/openshift-ansible/pull/4687 merged, please reopen it the issue still persists.
