### ISSUE TITLE
ERROR! the playbook: /root/openshift-ansible/playbooks/byo/config.yml could not be found

### ISSUE THREAD

**Issue by ChinmayanP** [openshift/openshift-ansible#6568]
#### Description
While running the RPM based installation i get the error  "ERROR! the playbook: /root/openshift-ansible/playbooks/byo/config.yml could not be found" . The command i ran was # ansible-playbook [-i /path/to/inventory] \
    ~/openshift-ansible/playbooks/byo/config.yml which as given https://docs.openshift.org/latest/install_config/install/advanced_install.html#running-the-advanced-installation. I pulled the openshift-ansible from this repo.  But the conig.yml file is missing in the git repo itself.

**Comment by jcperezamin** [comment]
Same error when I tried to test origin 3.7!.

**Comment by hareeshrao4839** [comment]
openshift-ansible/playbooks/deploy_cluster.yml

**Comment by subodhp** [comment]
Please mention the version of the RPM, I faced the same error, but it was resolved when I referenced to correct release version.

**Comment by jcperezamin** [comment]
Yes, still failing:
TASK [openshift_version : Get available origin version] **********************************************************************************************************************************
fatal: [openshift.educanube.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to openshift.educanube.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_cbf172/ansible_module_repoquery.py\", line 641, in <module>\r\n    main()\r\n  File \"/tmp/ansible_cbf172/ansible_module_repoquery.py\", line 631, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_cbf172/ansible_module_repoquery.py\", line 587, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File \"/tmp/ansible_cbf172/ansible_module_repoquery.py\", line 546, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, 'raw')\r\n  File \"/tmp/ansible_cbf172/ansible_module_repoquery.py\", line 384, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File \"/tmp/ansible_cbf172/ansible_module_repoquery.py\", line 355, in _run\r\n    stderr=subprocess.PIPE)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 0}

**Comment by ChinmayanP** [comment]
That config.yml is missing from the master baranch. buts it was present there till Release 3.7 branches

**Comment by ChinmayanP** [comment]
Tried the "openshift-ansible/playbooks/deploy_cluster.yml" in master branch and the installation stated. But it failed in logging installation .

Failure summary:


  1. Hosts:    
     Play:     OpenShift Aggregated Logging
     Task:     Waiting for logging-es-data-master-4huwyyl1 to finish scaling up
     Message:  Failed without returning a message.

**Comment by hetzbh** [comment]
@jcperezamin yeah, this fails because it tried to use Cockpit, so remove from your configuration file any line that mention cockpit ;)
Also, you'll need to install the package python-rhsm-certificates or else it won't be able to pull a redhat image (forgot what it's name)

**Comment by jcperezamin** [comment]
Is working out if you change to branch 3.7.

**Comment by hetzbh** [comment]
yup ;)

**Comment by davidaah** [comment]
More details are in https://github.com/openshift/openshift-ansible/issues/6503
