### ISSUE TITLE
Openshit Webconsole Install fails

### ISSUE THREAD

**Issue by jocelynthode** [openshift/openshift-ansible#8623]
#### Description

On a clean multi master setup install with  'redhat/openshift-ovs-multitenant' sdn. Openshift webconsole cannot start

##### Version
```
ansible 2.4.3.0

oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://REDACTED:443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

commit a31b673c4ecab2ed2f0bcd4635f7740d9bb3d8e5 (HEAD -> release-3.9, origin/release-3.9)
```

##### Steps To Reproduce
1. start `./openshift-ansible/playbooks/deploy_cluster.yml` playbook

##### Expected Results
Webconsole should come up

##### Observed Results
Console if failing to start due to CNI errors

```
Jun 04 17:28:20 p1docker1b origin-node[50178]: I0604 17:28:20.184309   50178 helpers.go:125] Unable to get network stats from pid 62049: couldn't read network stats: failure opening /proc/62049/net/dev: open /proc/62049/net/dev: no such file or directory

Jun 04 17:28:20 p1docker1b origin-node[50178]: I0604 17:28:20.185070   50178 cni.go:284] Got netns path /proc/62049/ns/net
Jun 04 17:28:20 p1docker1b origin-node[50178]: I0604 17:28:20.185085   50178 cni.go:285] Using podns path openshift-web-console
Jun 04 17:28:20 p1docker1b origin-node[50178]: I0604 17:28:20.185177   50178 cni.go:256] About to add CNI network cni-loopback (type=loopback)
Jun 04 17:28:20 p1docker1b origin-node[50178]: E0604 17:28:20.187044   50178 cni.go:259] Error adding network: failed to Statfs "/proc/62049/ns/net": no such file or directory
Jun 04 17:28:20 p1docker1b origin-node[50178]: E0604 17:28:20.187065   50178 cni.go:220] Error while adding to cni lo network: failed to Statfs "/proc/62049/ns/net": no such file or directory

Jun 04 17:28:20 p1docker1b origin-node[50178]: E0604 17:28:20.236188   50178 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "webconsole-5f649b49b5-4dgf5_openshift-web-console" network: failed to Statfs "/proc/62049/ns/net": no such file or directory

```

I also get this which I think is a red herring as the SA exists:
```
Error creating: pods \"webconsole-5f649b49b5-\" is forbidden: error looking up service account openshift-web-console/webconsole: serviceaccount \"webconsole\" not found", 
```
##### Additional Information

```
CentOS Linux release 7.5.1804 (Core) 

Kernel: 4.16.13-1.el7.elrepo.x86_64

NAME                         STATUS    ROLES     AGE       VERSION
master01   Ready     master    1h        v1.9.1+a0ce1bc657
master02  Ready     master    1h        v1.9.1+a0ce1bc657
master03   Ready     master    1h        v1.9.1+a0ce1bc657
infra01  Ready     <none>    1h        v1.9.1+a0ce1bc657
compute01   Ready     compute   1h        v1.9.1+a0ce1bc657
```

```

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# Ansible variables
ansible_ssh_user=ansible
ansible_become=yes

# Openshift common configuration
openshift_debug_level=2
openshift_deployment_type=origin
openshift_release="3.9"
openshift_install_examples=false
openshift_hosted_manage_router=false
openshift_hosted_manage_registry=false
openshift_check_min_host_memory_gb=8
openshift_disable_check=disk_availability
openshift_hostname_check=false
openshift_use_crio=false
#openshift_crio_use_rpm=true
#openshift_crio_enable_docker_gc=true


# Openshift OS Settings
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
os_firewall_use_firewalld=True
```

**Comment by jocelynthode** [comment]
Wrong selinux context on /var/lib/containers/docker

**Comment by vrutkovs** [comment]
IIRC running `prerequisites.yml` before `deploy_cluster.yml` should fix the SELinux context

**Comment by jocelynthode** [comment]
@vrutkovs I ran the prerequisites.yml but it didn't fix my selinux context. maybe becuase I had my docker in /var/lib/containers/docker and a symbolic link pointing to /var/lib/docker.

**Comment by cevn** [comment]
having the same issue. where my docker is symlinked somewhere else for space concerns. If prereqs doesn't fix it should that be a bug?

**Comment by bartimar** [comment]
edit the typo in subject please :D
