### ISSUE TITLE
Ansible/Origin 3.9 deployment fails because "package(s) are available at a version that is higher than requested"

### ISSUE THREAD

**Issue by alanbchristie** [openshift/openshift-ansible#9675]
#### Description

A week ago my deployment was perfectly fine. Then, without changing the base image of my instances or my orchestration steps all new deployments now start to fail during the `deploy_cluster.yml` play with the error:

```
One or more checks failed
     check "package_version":
               Some required package(s) are available at a version
               that is higher than requested
                 origin-3.10.0
                 origin-node-3.10.0
                 origin-master-3.10.0
               This will prevent installing the version you requested.
               Please check your enabled repositories or adjust openshift_release.
 ```

This problem simultaneously started to occur on my OpenStack and AWS deployments last week and the only way around the problem was to add to 'package_version` to `openshift_disable_check`. With this check disabled the deployment completed to yield a fully functional 3.9.

The "prerequisites" playbook keeps on adding the `CentOS-OpenShift-Origin.repo` even though the `CentOS-OpenShift-Origin39.repo` has been added.

##### Version

Ansible: -
```
$ ansible --version
ansible 2.5.7
  config file = /home/centos/abc/orchestrator/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

Repository info: -
```
$ git describe
openshift-ansible-3.9.40-1
```

##### Steps To Reproduce
1. The inventory (which was working last week) has `openshift_release=v3.9`. It doesn't matter if `openshift_image_tag` and `openshift_pkg_version` are set.
2. After creating the base instances run the `openshift-ansible/playbooks/prerequisites.yml` playbook. This should install the required repositories and it installs the `CentOS-OpenShift-Origin.repo` which seems to upset the following...
3. Run the `openshift-ansible/playbooks/deploy_cluster.yml` playbook. It will fail with the following: -

```
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "package_version":
               Some required package(s) are available at a version
               that is higher than requested
                 origin-3.10.0
                 origin-node-3.10.0
                 origin-master-3.10.0
               This will prevent installing the version you requested.
               Please check your enabled repositories or adjust openshift_release.
```

##### Expected Results
The `openshift-ansible/playbooks/deploy_cluster.yml` should not encounter this problem. A specific origin release has been named and yet the `prerequisites` play seems to install things that upset the `deploy_cluster` play.

##### Observed Results
The `deploy_cluster` fails because it's upset that it finds a 3.10 repo created by the `prerequisites`.

##### Additional Information

Key parts of the inventory (this is incomplete, and avoids company-specific material): -

```
[OSEv3:vars]
ansible_ssh_user=centos
ansible_become=yes

openshift_deployment_type=origin
openshift_release=v3.9
openshift_image_tag=v3.9.0
openshift_pkg_version=-3.9.0

openshift_disable_check=disk_availability,docker_storage,docker_image_availability,memory_availability
openshift_clock_enabled=true

openshift_master_api_port=443
openshift_master_console_port=443

osm_default_node_selector='zone=default'

openshift_docker_additional_registries=registry.access.redhat.com
openshift_docker_insecure_registries=registry.access.redhat.com

openshift_enable_unsupported_configurations=true

openshift_service_catalog_image_version=v3.9
```

Operating system: -

```
$ cat /etc/*-release
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
```

**Comment by DanyC97** [comment]
first thanks for moving the issue here, is easier to look at rather than on mailer.

so let's take it step by step ....

1) what @sdodson mentioned on dev mailer - ie https://github.com/openshift/openshift-ansible/pull/9549 it will part of the `openshift-ansible-3.9.41-1` tag which will be released (i'm building the rpm as we speak) into centOS repos tomorrow after 09:00 UTC (most likely it will be sync within 1 hour after the CI job completed).  With the PR in, the `keeps on adding the CentOS-OpenShift-Origin.repo even though the CentOS-OpenShift-Origin39.repo has been added` won't happen.

2) now regarding the `Some required package(s) are available at a that is higher than requested`, here the situation is as follow:

* the change is because a week or so ago i've tagged/ released 3.10 Origin rpms into `CentOS-OpenShift-Origin.repo` &  `CentOS-OpenShift-Origin310.repo`
8 because of the above i think we have uncovered a bug in `openshift-ansible/playbooks/deploy_cluster.yml` where it doesn't honor

```
openshift_release=v3.9
openshift_image_tag=v3.9.0
openshift_pkg_version=-3.9.0

```
@vrutkovs @sdodson @michaelgugino fyi the potential issue on the health check play. Imo it should take into account what is been defined in the inventory file and not bomb out.

**Comment by vrutkovs** [comment]
Fixed by #9549

**Comment by alanbchristie** [comment]
Does closing this also resolve the `potential issue on the health check play`? If not do we also need an issue to track that?

**Comment by powo** [comment]
running `deploy_cluster.yml` from the latest `release-3.9` installer still doesn't add the `centos-openshift-origin39` repo on nodes (of existing 3.9 cluster), and playbooks are therefore still throwing the `package_version` error.

BTW: regular OS updates caused the two "excluder" packages to be upgraded to 3.10 on all nodes:
```
# rpm -qa |grep origin
origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64
origin-3.9.0-1.el7.git.0.ba7faec.x86_64
origin-sdn-ovs-3.9.0-1.el7.git.0.ba7faec.x86_64
origin-excluder-3.10.0-1.el7.git.0.0c4577e.noarch         <===
origin-docker-excluder-3.10.0-1.el7.git.0.0c4577e.noarch  <===
origin-clients-3.9.0-1.el7.git.0.ba7faec.x86_64
origin-master-3.9.0-1.el7.git.0.ba7faec.x86_64
```
not sure if this will cause issues and needs to be downgraded (manually?) as soon as 39 repo is available

**Comment by ratheeshpc** [comment]
I am also facing same error , any solution here ?

**Comment by pheitman** [comment]
before running the openshift-ansible playbooks, install the 3.9-specific repos on your systems. I run

ansible all -i $INVENTORY -m yum -a "name=centos-release-openshift-origin39 state=present"  --become

to accomplish that.

**Comment by ratheeshpc** [comment]
Before that I tried as below and worked
set version to 3.10 , both Git and openshift_release
run uninstall playbook 
Remove Repo files or origin
Run prerequisites.yml then deploy_cluster.yml

This worked for me, Now trying to add CA signed certificates

**Comment by mtoddw** [comment]
I followed above, but failed. I had to add -e openshift_disable_check=package_version to install.  I have a working 3.9 cluster again. Does anyone know the reason or change that broke this?

**Comment by ratheeshpc** [comment]
I found that excluder package was 3.10 , So I did above step mentioned.
