### ISSUE TITLE
OKD 3.10 scale up playbook hang

### ISSUE THREAD

**Issue by Mikedu1988** [openshift/openshift-ansible#9792]
#### Description

Provide a brief description of your issue here. For example:

I recently installed OKD 3.10 cluster, 1 master 2 compute 1 infra.
today I wanted to scale up another compute node, the play book hangs for task:
TASK [Approve node certificates when bootstrapping]

It's wired that when I try oc get node, the new node is already in ready status, and I can deploy service into the new node. but I can't see the log of the pod.

I get below error when I ran diagnostic:
ERROR: [DNet2011 from diagnostic NetworkCheck@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/cluster/network/run_pod.go:219]
       [Creating remote tar locally failed: error dialing backend: dial tcp: lookup openshiftnode5.aidoin.com on 10.18.32.131:53: no such host, , Deleting remote logdir "/tmp/openshift/nodes/openshiftnode5.aidoin.com" on node "openshiftnode5.aidoin.com" failed: error dialing backend: dial tcp: lookup openshiftnode5.aidoin.com on 10.18.32.131:53: no such host, ]

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-openshift-ansible-3.10.36-1
```

##### Steps To Reproduce
1. install a cluster
2. add a new node

Inventory file are like below:
[inventory.txt](https://github.com/openshift/openshift-ansible/files/2327976/inventory.txt)

##### Expected Results
Describe what you expected to happen.
node are up and running correctly
```
Example command and output or error messages
```

##### Observed Results
the play book hang, and node is not running correctly

##### Additional Information
[root@openshift openshift-ansible-openshift-ansible-3.10.36-1]# oc get csr
NAME                                                   AGE       REQUESTOR                                                 CONDITION
csr-td2cx                                              36m       system:node:openshiftnode5.aidoin.com                     Approved,Issued
node-csr-SavYdlvGiC1o1Rh6TqDsXvYWolrBKcf0jOxML2TN87E   36m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
[root@openshift openshift-ansible-openshift-ansible-3.10.36-1]#

[root@openshift openshift-ansible-openshift-ansible-3.10.36-1]# oc get node
NAME                        STATUS    ROLES     AGE       VERSION
openshift.aidoin.com        Ready     master    7d        v1.10.0+b81c8f8
openshiftnode2.aidoin.com   Ready     compute   7d        v1.10.0+b81c8f8
openshiftnode3.aidoin.com   Ready     compute   7d        v1.10.0+b81c8f8
openshiftnode4.aidoin.com   Ready     infra     7d        v1.10.0+b81c8f8
openshiftnode5.aidoin.com   Ready     compute   37m       v1.10.0+b81c8f8
[root@openshift openshift-ansible-openshift-ansible-3.10.36-1]#

**Comment by Mikedu1988** [comment]
the test is still hanging after one night.
TASK [Approve node certificates when bootstrapping] ***********************************************************************************
Tuesday 28 August 2018  07:51:37 -0400 (0:00:00.189)       0:04:00.910 ********

But now I can't get any csr.
[root@openshift openshift-ansible-openshift-ansible-3.10.36-1]# oc get csr
No resources found.

**Comment by michaelgugino** [comment]
We have been working on the csr approval process as it has been very error prone.

We just merged some new code in that area on both master and 3.10 branches.  Are you able to try from latest release-3.10 branch?

**Comment by Mikedu1988** [comment]
tried again with the latest code in release-3.10 branch, still no luck, the task failed after 30 tries:
TASK [Approve node certificates when bootstrapping] ***********************************************************************************
FAILED - RETRYING: Approve node certificates when bootstrapping (2 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (1 retries left).
fatal: [openshift.aidoin.com]: FAILED! => {"attempts": 30, "changed": false, "msg": "Cound not find csr for nodes: openshiftnode5.aidoin.com", "state": "unknown"}

**Comment by Mikedu1988** [comment]
any workaround regarding this issue as we really need to scale up the cluster.

**Comment by aland-zhang** [comment]
I also encountered the same problem.
```
TASK [Approve node certificates when bootstrapping] *************************************************************************************
Wednesday 29 August 2018  11:10:12 +0800 (0:00:00.151)       0:18:18.062 ****** 
FAILED - RETRYING: Approve node certificates when bootstrapping (30 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (29 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (28 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (27 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (26 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (25 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (24 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (23 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (22 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (21 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (20 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (19 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (18 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (17 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (16 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (15 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (14 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (13 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (12 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (11 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (10 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (9 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (8 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (7 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (6 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (5 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (4 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (3 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (2 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (1 retries left).
fatal: [10.10.244.212]: FAILED! => {"attempts": 30, "changed": false, "msg": "Cound not find csr for nodes: 10-10-234-215, 10-10-233-116, 10-10-217-117", "state": "unknown"}
Failure summary:


  1. Hosts:    10.10.244.212
     Play:     Approve any pending CSR requests from inventory nodes
     Task:     Approve node certificates when bootstrapping
     Message:  Cound not find csr for nodes: 10-10-234-215, 10-10-233-116, 10-10-217-117
```

**Comment by Mikedu1988** [comment]
@DanyC97 
I was flowing the advice from michaelgugino, checkout the latest release-3.10 branch and try again.
so I switched to branch release-3.10 and ran git pull,then tried the playbook.

**Comment by michaelgugino** [comment]
@Mikedu1988 please create a gist/pastebin of verbose output (ansible-playbook -vvv) for task 'Approve node certificates when bootstrapping'

Are there any pending csrs?  'oc get csr' ?  If so, please run:
'oc get csr -ojson'

and share output.

In either case, run: 
'oc get --raw /api/v1/nodes/openshiftnode5.aidoin.com/proxy/healthz'

We use that api endpoint to determine if the node's server certificate is valid and working.  If that fails and you don't have any outstanding csrs, you may be having network or firewall issues, or the node itself may be broken in some way.  You'll need to troubleshoot.

**Comment by michaelgugino** [comment]
@aland-zhang 

Please share output of
'oc get csr' and 'oc get csr -ojson' in a gist/pastebin.

**Comment by Mikedu1988** [comment]
OK I'll get it today. thanks

**Comment by Mikedu1988** [comment]
@michaelgugino 
`Using module file /home/mike.du/openshift-ansible/roles/lib_openshift/library/oc_csr_approve.py
<openshift.aidoin.com> ESTABLISH SSH CONNECTION FOR USER: root
<openshift.aidoin.com> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r openshift.aidoin.com '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<openshift.aidoin.com> (1, '\n{"exception": "  File \\"/tmp/ansible_oQLbOi/ansible_module_oc_csr_approve.py\\", line 24, in <module>\\n    from json.decoder import JSONDecodeError\\n", "changed": false, "failed": true, "state": "unknown", "invocation": {"module_args": {"oc_bin": "oc", "oc_conf": "/etc/origin/master/admin.kubeconfig", "node_list": ["openshiftnode5.aidoin.com"]}}, "msg": "Cound not find csr for nodes: openshiftnode5.aidoin.com"}\n', '')
FAILED - RETRYING: Approve node certificates when bootstrapping (18 retries left).Result was: {
    "attempts": 13,
    "changed": false,
    "invocation": {
        "module_args": {
            "node_list": [
                "openshiftnode5.aidoin.com"
            ],
            "oc_bin": "oc",
            "oc_conf": "/etc/origin/master/admin.kubeconfig"
        }
    },
    "msg": "Cound not find csr for nodes: openshiftnode5.aidoin.com",
    "retries": 31,
    "state": "unknown"
}`

The log says could not fine the csr for node, but oc get csr can clearly see the csr is there:
`[root@openshift ~]# oc get csr
NAME                                                   AGE       REQUESTOR                                                 CONDITION
csr-4mfgf                                              46s       system:node:openshiftnode5.aidoin.com                     Approved,Issued
node-csr-eVb5CzlWeRmFxFg0zl80n1iTAUvY1DQB8BjCqpzp_cQ   49s       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
[root@openshift ~]#
`

**Comment by aland-zhang** [comment]
oc get csr -ojson
```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "certificates.k8s.io/v1beta1",
            "kind": "CertificateSigningRequest",
            "metadata": {
                "creationTimestamp": "2018-08-31T06:19:56Z",
                "generateName": "csr-",
                "name": "csr-6xtdh",
                "namespace": "",
                "resourceVersion": "710",
                "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-6xtdh",
                "uid": "e19a0a31-ace5-11e8-9f5d-525400614a73"
            },
            "spec": {
                "groups": [
                    "system:masters",
                    "system:cluster-admins",
                    "system:authenticated"
                ],
                "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIMk1JR2RBZ0VBTURzeEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVpTUNBR0ExVUVBeE1aYzNsegpkR1Z0T201dlpHVTZNVEF0TVRBdE1qUTBMVEl4TWpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJMNnlnVkE4Q2tPUEgyMDhnUVZxWUFjNisydFlBakZaNWZwUlRGRlpsS2pLNE9DVjhLejZyUUtoYmtwUmwyQTkKZUVpeXhvZTdvdkwzSnQ1K3Qwb1lIZTJnQURBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQS8rRHFqejNvOGVOUwpYWGwwYjcyWlNRckc1U3IvWXZ5QkNZV0Jmektxc2lJQ0lDeWExUUxNdS9JT3BXZndTRllGUUVCaUU5ck5DV2dLCjVKc3dad1FQRlRXcAotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K",
                "usages": [
                    "digital signature",
                    "key encipherment",
                    "client auth"
                ],
                "username": "system:admin"
            },
            "status": {
                "conditions": [
                    {
                        "lastUpdateTime": "2018-08-31T06:24:48Z",
                        "message": "This CSR was approved by kubectl certificate approve.",
                        "reason": "KubectlApprove",
                        "type": "Approved"
                    }
                ]
            }
        },
        {
            "apiVersion": "certificates.k8s.io/v1beta1",
            "kind": "CertificateSigningRequest",
            "metadata": {
                "creationTimestamp": "2018-08-31T06:24:37Z",
                "generateName": "csr-",
                "name": "csr-mzkmj",
                "namespace": "",
                "resourceVersion": "682",
                "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-mzkmj",
                "uid": "892ca208-ace6-11e8-9f5d-525400614a73"
            },
            "spec": {
                "groups": [
                    "system:masters",
                    "system:cluster-admins",
                    "system:authenticated"
                ],
                "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkxqQ0IxZ0lCQURBN01SVXdFd1lEVlFRS0V3eHplWE4wWlcwNmJtOWtaWE14SWpBZ0JnTlZCQU1UR1hONQpjM1JsYlRwdWIyUmxPakV3TFRFd0xUSTBOQzB5TVRJd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUnBtS25KMWtTd080OTdIV1JzNlRXVWtIeS9Yc3NxQ0RFV0E2U1p3bmZaZ1dJeUZPTzA4WGZkR2xybHpMcE0KTmNwbG9yd290cW5yN09ZTTZVdGxwbHYvb0Rrd053WUpLb1pJaHZjTkFRa09NU293S0RBbUJnTlZIUkVFSHpBZApnZzB4TUMweE1DMHlORFF0TWpFeWdnQ0hCQW9LOU5TSEJLd1JBQUV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnCmZldERyWlpqTElxbmxiRXIybUh6aml4SzhjTy82UnBscDZZbWFTT1dzSzhDSUdISHF0Mm1IdGZTT1FTWFRTNkUKbW8rN2F1QVF6V2RFRUlWMWhJb1dJTXAyCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=",
                "usages": [
                    "digital signature",
                    "key encipherment",
                    "server auth"
                ],
                "username": "system:admin"
            },
            "status": {}
        },
        {
            "apiVersion": "certificates.k8s.io/v1beta1",
            "kind": "CertificateSigningRequest",
            "metadata": {
                "creationTimestamp": "2018-08-31T06:19:56Z",
                "generateName": "csr-",
                "name": "csr-sqxch",
                "namespace": "",
                "resourceVersion": "245",
                "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-sqxch",
                "uid": "e165574b-ace5-11e8-9f5d-525400614a73"
            },
            "spec": {
                "groups": [
                    "system:masters",
                    "system:cluster-admins",
                    "system:authenticated"
                ],
                "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQk1EQ0IxZ0lCQURBN01SVXdFd1lEVlFRS0V3eHplWE4wWlcwNmJtOWtaWE14SWpBZ0JnTlZCQU1UR1hONQpjM1JsYlRwdWIyUmxPakV3TFRFd0xUSTBOQzB5TVRJd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUzVVdGRxSkdibEFZM0pNbDNxUHYrNHc4WXYyQUxteklhT3NaeFVUdFBmWVBGM2JuOGZEUy9XVytJd1d2VVEKK1dnTkZKRE55dzdxKzJsV00xZFdaaW5Zb0Rrd053WUpLb1pJaHZjTkFRa09NU293S0RBbUJnTlZIUkVFSHpBZApnZzB4TUMweE1DMHlORFF0TWpFeWdnQ0hCQW9LOU5TSEJLd1JBQUV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loCkFLYXorc3YrZWdBOVFJMXlPSVBxYWdFL2I3TE8yT3BQNXU4LytyUjh5Ym9yQWlFQThjQ3U1UFVMR290U2JRN2gKaTV0Ry9DaDdhT256YjVoaUp6aklYL1dndGprPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K",
                "usages": [
                    "digital signature",
                    "key encipherment",
                    "server auth"
                ],
                "username": "system:admin"
            },
            "status": {}
        },
        {
            "apiVersion": "certificates.k8s.io/v1beta1",
            "kind": "CertificateSigningRequest",
            "metadata": {
                "creationTimestamp": "2018-08-31T06:24:38Z",
                "name": "node-csr-Bs8es-ZMExIACgTOVprx2UkCf3uEvBJlhdcCnHcIQl4",
                "namespace": "",
                "resourceVersion": "706",
                "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/node-csr-Bs8es-ZMExIACgTOVprx2UkCf3uEvBJlhdcCnHcIQl4",
                "uid": "8972e848-ace6-11e8-9f5d-525400614a73"
            },
            "spec": {
                "groups": [
                    "system:serviceaccounts",
                    "system:serviceaccounts:openshift-infra",
                    "system:authenticated"
                ],
                "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIM01JR2RBZ0VBTURzeEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVpTUNBR0ExVUVBeE1aYzNsegpkR1Z0T201dlpHVTZNVEF0TVRBdE1qTXpMVEV4TmpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJDRXg3MzhaT0hZTjJiVk11aGgyTmliY2ZMQ3ZCd0tyWUJkSHhJV09ROE00T21IUEpjeVRybHByQmFoS2E3U2wKSVdvUTdWUmdSaTFXUFFxT3dPWWcvZWlnQURBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQW42bk9qamwvQXN2QQp3SytaRTVJMi95aGhoSTQ1cDZYU1NoM0cyQU9lUGRBQ0lRQ21vcHpYNEU5NksxTUREZkFzSWFxQ1JEdGV6U0RtClc1SElqcC9OR0RMTHpBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==",
                "uid": "df0e5a77-ace5-11e8-9f5d-525400614a73",
                "usages": [
                    "digital signature",
                    "key encipherment",
                    "client auth"
                ],
                "username": "system:serviceaccount:openshift-infra:node-bootstrapper"
            },
            "status": {
                "conditions": [
                    {
                        "lastUpdateTime": "2018-08-31T06:24:46Z",
                        "message": "This CSR was approved by kubectl certificate approve.",
                        "reason": "KubectlApprove",
                        "type": "Approved"
                    }
                ]
            }
        },
        {
            "apiVersion": "certificates.k8s.io/v1beta1",
            "kind": "CertificateSigningRequest",
            "metadata": {
                "creationTimestamp": "2018-08-31T06:24:38Z",
                "name": "node-csr-sA9ciONmL2zKK72h28v0DnY3ygNuhfvFTeTV4rJF8VU",
                "namespace": "",
                "resourceVersion": "707",
                "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/node-csr-sA9ciONmL2zKK72h28v0DnY3ygNuhfvFTeTV4rJF8VU",
                "uid": "8975339a-ace6-11e8-9f5d-525400614a73"
            },
            "spec": {
                "groups": [
                    "system:serviceaccounts",
                    "system:serviceaccounts:openshift-infra",
                    "system:authenticated"
                ],
                "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIMU1JR2RBZ0VBTURzeEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVpTUNBR0ExVUVBeE1aYzNsegpkR1Z0T201dlpHVTZNVEF0TVRBdE1qRTNMVEV4TnpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJHNXNwSkdRODdrdG9oSkVuS0lUTE45bXBYRXBxT3RLK3lkWllMdS9ycG9JTmNVaS90b1EzMW55VkhZeFM3bG4KVXFUd3NvcHJMby9jYUgrc05QSDMwc3lnQURBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCdmpzWS9qY1d0Y1RkcgpVMFZHUFFXQm12bncxTy9EZWsralBOYXRXTElHSlFJZ1BrTjZYZ2oxUVhHbkJkdWcyckJFVGszeDdDSzlJVWk1CmMrWXRGMjYvTm9VPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K",
                "uid": "df0e5a77-ace5-11e8-9f5d-525400614a73",
                "usages": [
                    "digital signature",
                    "key encipherment",
                    "client auth"
                ],
                "username": "system:serviceaccount:openshift-infra:node-bootstrapper"
            },
            "status": {
                "conditions": [
                    {
                        "lastUpdateTime": "2018-08-31T06:24:47Z",
                        "message": "This CSR was approved by kubectl certificate approve.",
                        "reason": "KubectlApprove",
                        "type": "Approved"
                    }
                ]
            }
        },
        {
            "apiVersion": "certificates.k8s.io/v1beta1",
            "kind": "CertificateSigningRequest",
            "metadata": {
                "creationTimestamp": "2018-08-31T06:24:38Z",
                "name": "node-csr-uXRTalus24z0g1aUve9f3GeUvvCvDA09u46ZzmkreqE",
                "namespace": "",
                "resourceVersion": "712",
                "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/node-csr-uXRTalus24z0g1aUve9f3GeUvvCvDA09u46ZzmkreqE",
                "uid": "898c62fa-ace6-11e8-9f5d-525400614a73"
            },
            "spec": {
                "groups": [
                    "system:serviceaccounts",
                    "system:serviceaccounts:openshift-infra",
                    "system:authenticated"
                ],
                "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIM01JR2RBZ0VBTURzeEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVpTUNBR0ExVUVBeE1aYzNsegpkR1Z0T201dlpHVTZNVEF0TVRBdE1qTTBMVEl4TlRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJBU2ZaK05ZdGZZY0hqRXpxQU4rMUE2S3VTY3c0aTNuMDhBZ0Q4UmRUOFl6SVZzbHNYYTZFOWtuYWtsU1Y3ZUsKWTVDTGhDNm5zc0FqNUMxUEJQbDJmcHVnQURBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWxWY3V5OVhDSkdpagpWS2hiUi9TaHJzM2pLcmNiNU0vRDU0M0Mrck5zdWxzQ0lRRFVBRWlGSmlFV05MdWNkNCsrcEQza245N1VTci9jClF2bTIzcVc5aTh2ZndBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==",
                "uid": "df0e5a77-ace5-11e8-9f5d-525400614a73",
                "usages": [
                    "digital signature",
                    "key encipherment",
                    "client auth"
                ],
                "username": "system:serviceaccount:openshift-infra:node-bootstrapper"
            },
            "status": {
                "conditions": [
                    {
                        "lastUpdateTime": "2018-08-31T06:24:49Z",
                        "message": "This CSR was approved by kubectl certificate approve.",
                        "reason": "KubectlApprove",
                        "type": "Approved"
                    }
                ]
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

**Comment by aland-zhang** [comment]
It has been used for orgin-ansible for more than two years. The version of 3.10 has the most problems. It has not been installed successfully for one month.

**Comment by feld-ims** [comment]
I am running into the same issue "Cound not find csr for nodes" as well, from a 3.9 > 3.10 upgrade. Been trying to upgrade for weeks and it seems like it's some new error with the playbooks every time.

**Comment by michaelgugino** [comment]
@Mikedu1988 you didn't provide everything I asked, see the following:

Are there any pending csrs? 'oc get csr' ? If so, please run:
'oc get csr -ojson'

and share output.

In either case, run:
'oc get --raw /api/v1/nodes/openshiftnode5.aidoin.com/proxy/healthz'

We use that api endpoint to determine if the node's server certificate is valid and working. If that fails and you don't have any outstanding csrs, you may be having network or firewall issues, or the node itself may be broken in some way. You'll need to troubleshoot.

**Comment by michaelgugino** [comment]
@aland-zhang the module appears to be work correctly, I don't think your nodes are creating csrs, they are likely failing to start for some reason.  I suggest you start with a simple environment and work your way there.  Lots of things have changed in 3.10 and I can't speculate why you're having these problems.  If you want to open a new issue, please provide inventory and all variables, full verbose output (-vvv) log, and fill out the rest of the information requested in the issue.

**Comment by aland-zhang** [comment]
ansible-playbook  playbooks/deploy_cluster.yml -vvv
```
Using module file /root/openshift/openshift-ansible-openshift-ansible-3.10.41-1/roles/lib_openshift/library/oc_csr_approve.py
<10.10.244.212> ESTABLISH SSH CONNECTION FOR USER: zhangwenhua
<10.10.244.212> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o Port=60000 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publicke
y -o PasswordAuthentication=no -o User=zhangwenhua -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r 10.10.244.212 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=qahmnvaersxwctclvzkzwcshlvwzoedj] password: " 
-u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qahmnvaersxwctclvzkzwcshlvwzoedj; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<10.10.244.212> (1, '\n{"exception": "  File \\"/tmp/ansible_dFaaDz/ansible_module_oc_csr_approve.py\\", line 24, in <module>\\n    from json.decoder import JSONDecodeError\\n", "changed": false, "failed": true, "state": "unkno
wn", "invocation": {"module_args": {"oc_bin": "oc", "oc_conf": "/etc/origin/master/admin.kubeconfig", "node_list": ["10-10-244-212", "10-10-234-215", "10-10-233-116", "10-10-217-117"]}}, "msg": "Cound not find csr for nodes: 10
-10-234-215, 10-10-233-116, 10-10-217-117"}\n', '')
The full traceback is:
  File "/tmp/ansible_dFaaDz/ansible_module_oc_csr_approve.py", line 24, in <module>
    from json.decoder import JSONDecodeError

fatal: [10.10.244.212]: FAILED! => {
    "attempts": 30, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "node_list": [
                "10-10-244-212", 
                "10-10-234-215", 
                "10-10-233-116", 
                "10-10-217-117"
            ], 
            "oc_bin": "oc", 
            "oc_conf": "/etc/origin/master/admin.kubeconfig"
        }
    }, 
    "msg": "Cound not find csr for nodes: 10-10-234-215, 10-10-233-116, 10-10-217-117", 
    "state": "unknown"
}

PLAY RECAP *******************************************************************************************************
10.10.217.117              : ok=25   changed=1    unreachable=0    failed=0  slave
10.10.233.116              : ok=25   changed=1    unreachable=0    failed=0  slave
10.10.234.215              : ok=59   changed=4    unreachable=0    failed=0  slave
10.10.244.212              : ok=285  changed=56   unreachable=0    failed=1   master
localhost                  : ok=13   changed=0    unreachable=0    failed=0

PLAY RECAP ************************************************************************************************************************************************************************************************************************
10.10.217.117              : ok=25   changed=1    unreachable=0    failed=0
10.10.233.116              : ok=25   changed=1    unreachable=0    failed=0
10.10.234.215              : ok=59   changed=4    unreachable=0    failed=0
10.10.244.212              : ok=285  changed=56   unreachable=0    failed=1   
localhost                  : ok=13   changed=0    unreachable=0    failed=0


INSTALLER STATUS ******************************************************************************************************************************************************************************************************************
Initialization              : Complete (0:02:06)
Health Check                : Complete (0:00:01)
Node Bootstrap Preparation  : Complete (0:00:20)
etcd Install                : Complete (0:00:46)
Master Install              : Complete (0:08:39)
Master Additional Install   : Complete (0:00:51)
Node Join                   : In Progress (0:04:13)
        This phase can be restarted by running: playbooks/openshift-node/join.yml

Failure summary:


  1. Hosts:    10.10.244.212
     Play:     Approve any pending CSR requests from inventory nodes
     Task:     Approve node certificates when bootstrapping
     Message:  Cound not find csr for nodes: 10-10-234-215, 10-10-233-116, 10-10-217-117
```
```
cat /etc/hosts  in nodes: 10-10-234-215, 10-10-233-116, 10-10-217-117                                                                                                                                                                     
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.10.244.212  10-10-244-212
10.10.234.215  10-10-234-215
10.10.217.117  10-10-217-117
10.10.233.116  10-10-233-116

ping 10-10-234-215                                                                               
PING 10-10-234-215 (10.10.234.215) 56(84) bytes of data.
64 bytes from 10-10-234-215 (10.10.234.215): icmp_seq=1 ttl=64 time=1.00 ms
64 bytes from 10-10-234-215 (10.10.234.215): icmp_seq=2 ttl=64 time=0.393 ms
```

**Comment by Mikedu1988** [comment]
I deployed some service on node5, everything is working fine except for the logs. My work around is to check the logs using docker logs on node5 itself.

On this weekend, I'll clean the cluster and reinstall, we shall see what happens next.

Anyway, I really appreciate anyone who tried to help, I'll not comment on this issue again, but I'll leave it open for you to discuss.

**Comment by BrianHolsen** [comment]
@Mikedu1988 
I encountered the same problem when add a new host [compute-02]. But the node is `Ready` in `oc get node`
I try to drain it, and `oc delete node xxx` to remove it. On [compute-02], I stopped `origin-node` service, and delete all contents in `/etc/origin`. Then, on **ALL HOSTS**, restart `dnsmasq` service to reload `/etc/hosts`.
And it worked.
You may try it out. I'll add another new node later to see if it could solve the issue.

**Comment by BrianHolsen** [comment]
I tried the following steps to add a new node [compute-03], it works fine.

1. Create and prep new node `compute-03`
1. Edit `/etc/hosts` on **all hosts**
    ```text
    10.100.11.103 compute-03
    ```
1. Restart `dnsmasq` service on **all hosts** except compute-03 (dnsmasq not installed)
    ```shell
    systemctl restart dnsmasq
    ```
1. Edit `/etc/ansible/hosts`, add `compute-03` under `[new_nodes]` section
1. Run scaleup.yml

**Comment by Mikedu1988** [comment]
@BrianHolsen I'll try later this week. Thanks

**Comment by michaelgugino** [comment]
@Mikedu1988 @aland-zhang @BrianHolsen 

We don't support /etc/hosts for nodes. You must have working DNS, that is likely the cause of these issues.

**Comment by powertim** [comment]
Hi,

I have the problem on version 3.10 too.
Result of oc get csr:
[openshifto@gvaawxdb02p openshift-ansible]$ oc get csr
NAME                                                   AGE       REQUESTOR                                                 CONDITION
csr-4z2zv                                              40m       system:node:gvaawxdb02p                                   Approved,Issued
csr-58x27                                              51m       system:node:gvaawxdb02p                                   Approved,Issued
csr-867j6                                              42m       system:node:gvaawxdb02p                                   Approved,Issued
csr-8ts66                                              28m       system:node:gvaawxdb02p                                   Approved,Issued
csr-bmpw5                                              1h        system:admin                                              Approved,Issued
csr-dthwn                                              24m       system:node:gvaawxapp05p                                  Approved,Issued
csr-hplpr                                              27m       system:node:gvaawxdb02p                                   Approved,Issued
csr-mbk79                                              24m       system:node:gvaawxapp04p                                  Approved,Issued
csr-nfkxq                                              1h        system:admin                                              Approved,Issued
csr-ngnz7                                              24m       system:node:gvaawxdb02p                                   Approved,Issued
csr-xshxl                                              24m       system:node:gvaawxapp06p                                  Approved,Issued
node-csr-CSkUv4SoyVXkxdCTIfY5EcvA1i_yAuAxEiXA6stOP64   24m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-PfJ80Ii37O0w9fi_2nVzE-TJCqhs1PDEMzc4sgWqubQ   24m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-xyRZRwFe-TqR9-hjCAfwBCoNDwMHnUTA5bPlDUCyei0   24m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued

Error message of playbook deploy_cluster.yml:
TASK [Approve node certificates when bootstrapping] *************************************************************************************************************************************************
Friday 21 September 2018  15:48:02 +0200 (0:00:00.102)       0:00:32.815 ******
FAILED - RETRYING: Approve node certificates when bootstrapping (30 retries left).
FAILED - RETRYING: Approve node certificates when bootstrapping (29 retries left).
etc....

Failure summary:

  1. Hosts:    gvaawxdb02p.org.contoso
     Play:     Approve any pending CSR requests from inventory nodes
     Task:     Approve node certificates when bootstrapping
     Message:  Could not find csr for nodes: gvaawxdb02p, gvaawxapp05p, gvaawxapp06p, gvaawxapp04p

Please help me, it drives me crazy !
DNS **is** working.

**Comment by michaelgugino** [comment]
@powertim please file a new issue and include all the information, including -vvv (3 v's, not 2) output of the failed task.

Also, this is broken in currently released rpms for some users, I suggest trying the tip of the 3.10 branch from github.

**Comment by michaelgugino** [comment]
I'm locking this thread.  Anyone having an issue, please file your own GH issue as each case may not be related even if it appears as such.  "Help me!" and "Me too" are not sufficient in this case.
